version: '2.0'
services:
  bot:
    build:
      context: ./
      dockerfile: bot/Dockerfile-dev
    container_name: ana3bot
    restart: always
    env_file:
      env.env
    volumes:
      - ./bot:/usr/src/app
